%YAML:1.0
---
model_type: PINHOLE
camera_name: camera
image_width: 672
image_height: 376
distortion_parameters:
   k1: 0
   k2: 0
   p1: 0
   p2: 0
projection_parameters:
   org_width: 672
   org_height: 376
   fx: 264.0
   fy: 263.7
   cx: 343.76
   cy: 183.8795
