%YAML:1.0
---
model_type: PINHOLE
camera_name: camera
image_width: 672
image_height: 376
distortion_parameters:
   k1: 0
   k2: 0
   p1: 0
   p2: 0
projection_parameters:
   org_width: 672
   org_height: 376
   fx: 264.405
   fy: 264.245
   cx: 338.005
   cy: 186.8945
