%YAML:1.0

#common parameters
#support: 1 imu 1 cam; 1 imu 2 cam: 2 cam; 
imu: 1         
num_of_cam: 1  
length: 0.78
KINEMATIC: 0
agent_number: 3
agent_all: 3
ground_topic: "/vrpn_client_node/ag1312/pose"
imu_topic: "mavros/imu/data"
image0_topic: "cam3"
output_path: "/home/f404/output/agent3"

cam0_calib: "uecam.yaml"
image_width: 640
image_height: 480
   

# Extrinsic parameter between IMU and Camera.
estimate_extrinsic: 1   # 0  Have an accurate extrinsic parameters. We will trust the following imu^R_cam, imu^T_cam, don't change it.
                        # 1  Have an initial guess about extrinsic parameters. We will optimize around your initial guess.
body_world_T: !!opencv-matrix
  rows: 4
  cols: 4
  dt: d
  data : [0.71963119949,0.220833894775,-0.658303370521,-1.22900372878,
       0.487523234113,0.51438778303,0.705497204013,-2.02304876137,
       0.494420906638,-0.828635987384,0.262507842722,-2.00691086557,
       0.0,0.0,0.0,1.0]
  #data : [0.63432513065,-0.598032751797,-0.489886166782,-1.01406518382,
  #      0.519066690251,0.799082071305,-0.303377016912,-1.75672429596,
  #      0.572888645112,-0.0618439253025,0.817296720418,-1.8498997601,
  #      0.0,0.0,0.0,1.0]
scale: 0.61640588159
#scale: 32.4540270617
body_T_cam0: !!opencv-matrix
   rows: 4
   cols: 4
   dt: d
   data: [0, 0, 1, 0.200,
           1,0,0,  0,
           0,1,0, 0,
           0, 0, 0, 1]

#Multiple thread support
multiple_thread: 1

#feature traker paprameters
max_cnt: 100            # max feature number in feature tracking
min_dist: 30            # min distance between two features 
freq: 15                # frequence (Hz) of publish tracking result. At least 10Hz for good estimation. If set 0, the frequence will be same as raw image 
F_threshold: 1.0        # ransac threshold (pixel)
show_track: 1           # publish tracking image as topic
flow_back: 1            # perform forward and backward optical flow to improve feature tracking accuracy

#optimization parameters
max_solver_time: 0.04  # max solver itration time (ms), to guarantee real time
max_num_iterations: 8   # max solver itrations, to guarantee real time
keyframe_parallax: 10.0 # keyframe selection threshold (pixel)

#imu parameters       The more accurate parameters you provide, the better performance
acc_n: 0.2          # accelerometer measurement noise standard deviation. #0.2   0.04
gyr_n: 0.5         # gyroscope measurement noise standard deviation.     #0.05  0.004
acc_w: 0.2        # accelerometer bias random work noise standard deviation.  #0.02
gyr_w: 4.0e-2       # gyroscope bias random work noise standard deviation.     #4.0e-5
g_norm: 9.805       # gravity magnitude

#unsynchronization parameters
estimate_td: 1                      # online estimate time offset between camera and imu
td: 0.0                             # initial value of time offset. unit: s. readed image clock + td = real image clock (IMU clock)

#loop closure parameters
load_previous_pose_graph: 0        # load and reuse previous pose graph; load from 'pose_graph_save_path'
pose_graph_save_path: "~/output/pose_graph/" # save and load path
save_image: 1                   # save image in pose graph for visualization prupose; you can close this function by setting 0 
